name: Deploy Production

on:
  workflow_run:
    workflows: ["Publish Image"]
    types: [completed]

  workflow_dispatch:
    inputs:
      image_tag:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

      VM_HOST: ${{ secrets.VM_HOST }}
      VM_USER: ${{ secrets.VM_USER }}
      VM_APP_DIR: ${{ secrets.VM_APP_DIR }}

      VM_SSH_KEY_B64: ${{ secrets.VM_SSH_KEY_B64 }}

      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}

    steps:
      - name: Select image tag
        id: tag
        run: |
          if [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ]; then
            echo "image_tag=${{ inputs.image_tag }}" >> $GITHUB_OUTPUT
          else
            sha=$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-7)
            echo "image_tag=sha-$sha" >> $GITHUB_OUTPUT
          fi

      - name: Login to ECR
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Setup SSH
        run: |
          echo "$VM_SSH_KEY_B64" | base64 -d > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          IMAGE="$ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.tag.outputs.image_tag }}"

          ssh -i key.pem -o StrictHostKeyChecking=no $VM_USER@$VM_HOST <<EOF
          set -e

          cd $VM_APP_DIR

          export IMAGE_TAG="${{ steps.tag.outputs.image_tag }}"
          export POSTGRES_PASSWORD="$POSTGRES_PASSWORD"
          export GRAFANA_ADMIN_PASSWORD="$GRAFANA_ADMIN_PASSWORD"

          docker login -u AWS -p "$(aws ecr get-login-password --region $AWS_REGION)" $ECR_REGISTRY

          docker pull $IMAGE

          docker compose -f docker-compose.vm.yml up -d

          docker ps
          EOF
